### ISSUE TITLE
does not contain a definition for 'AddDbProvider'

### ISSUE THREAD

**Issue by pranav-manik** [PoisnFang/Poisn.GraphQL#3]
where is AddDbProvider importing from in Startup.cs?
services.AddDbProvider(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
I'm recieving this error:
Severity Code Description Project File Line Suppression State Error CS1061 'IServiceCollection' does not contain a definition for 'AddDbProvider' and no accessible extension method 'AddDbProvider' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)

**Comment by PizzaConsole** [comment]
When is it throwing this error?

**Comment by pranav-manik** [comment]
I should have been more clear I am trying to configure my own project with GraphQL and I was following your Startup.cs 
the following line gave me an import error

`services.AddDbProvider(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));`

error:
`Severity Code Description Project File Line Suppression State Error CS1061 'IServiceCollection' does not contain a definition for 'AddDbProvider' and no accessible extension method 'AddDbProvider' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)`

**Comment by PizzaConsole** [comment]
Ah, yes check the comments I just added: Which Db provider do you want to add?

```csharp
            //Db Connection is in appsettings.json
            // this adds in EF Core Db
            services.AddDbContext<ApplicationDbContext>(options =>
               options.UseSqlServer(
                   Configuration.GetConnectionString("DefaultConnection")), ServiceLifetime.Scoped);

            // this add in YesSql Db
            services.AddDbProvider(options =>
            options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
```
